version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: cally-ollama-dev
    restart: unless-stopped
    volumes:
      - ollama_dev_data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3

  cally:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cally-app-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  ollama_dev_data:
    driver: local
  bundle_cache:
    driver: local

networks:
  default:
    name: cally-dev-network
